plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

filters:
  instance-state-name: running

hostnames:
  - tag:Name
  - private-ip-address
  - public-ip-address
  - dns-name
  - instance-id

compose:
  # Use instance ID for connection (SSM plugin requires it)
  ansible_host: instance_id
  # Make human-readable inventory hostnames (e.g., jenkins-172.21.0.11)
  inventory_hostname: |
    {{
      (tags.Name | default('')) ~ '-' ~ private_ip_address
      if (tags.Name is defined and private_ip_address is defined)
      else instance_id
    }}
  ansible_connection: "'community.aws.aws_ssm'"
  ansible_aws_ssm_bucket_name: "'my-app-bucket-1337'"
  ansible_aws_ssm_region: "'us-east-1'"

keyed_groups:
  - prefix: tag
    key: tags
