- name: Initial Admin Password
  hosts: jenkins-ec2
  remote_user: ubuntu
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Get Jenkins initial admin password
      ansible.builtin.shell: docker exec $(docker ps -q) /bin/cat /var/jenkins_home/secrets/initialAdminPassword
      register: jenkins_password
      changed_when: false
    - name: Print Jenkins initial admin password
      ansible.builtin.debug:
        msg: "The Jenkins initial admin password is {{ jenkins_password.stdout }}"
