- name: All hosts
  hosts: all
  remote_user: ubuntu
  tasks:
    - name: Ping all
      ansible.builtin.ping:
- name: One host, by name
  hosts: prometheus-ec2
  remote_user: ubuntu
  tasks:
    - name: Ping
      ansible.builtin.ping:
- name: Multiple Hosts, by name
  hosts: jenkins-ec2:prometheus-ec2
  remote_user: ubuntu
  tasks:
    - name: Ping
      ansible.builtin.ping:
- name: One group, hosts in Cost Center department_b (AWS hosts with tag cost_center=department-b)
  hosts: tag_cost_center_department_b
  remote_user: ubuntu
  tasks:
    - name: Ping
      ansible.builtin.ping:
- name: Multiple groups, hosts in Cost Center department_a or in department_b (AWS hosts with tag cost_center=department_a or cost_center=department_b)
  hosts: tag_cost_center_department_a:tag_cost_center_department_b
  remote_user: ubuntu
  tasks:
    - name: Ping
      ansible.builtin.ping:
- name: Intersection of groups, all hosts running Ubuntu version 24.04 (AWS hosts with tag os=ubuntu AND tag os_ver=24_04)
  hosts: tag_os_ubuntu:&tag_os_ver_24_04
  remote_user: ubuntu
  tasks:
    - name: Ping
      ansible.builtin.ping:
